obj-y				:=

obj-y				+= common.o
obj-y				+= clock.o
obj-y				+= boot1.o
obj-y				+= contrast.o
obj-y				+= sram.o
obj-y				+= keypad.o

obj-$(CONFIG_MACH_NSPIRECX)	+= nspire_cx.o

obj-$(CONFIG_MACH_NSPIRECLP)	+= nspire_clp.o
obj-$(CONFIG_MACH_NSPIRECLP)	+= classic.o

obj-$(CONFIG_MACH_NSPIRETP)	+= nspire_tp.o
obj-$(CONFIG_MACH_NSPIRETP)	+= classic.o
